[project]
name = "lab"
authors = [
    {name = "Rafael Ferguson", email = "rafaelvferguson@gmail.com"},
]
maintainers = [
    {name = "Rafael Ferguson", email = "rafaelvferguson@gmail.com"}
]
dynamic = ["version"]
readme = "README.md"

[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["lab*"]

[tool.setuptools_scm]
version_file = "lab/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "node-and-timestamp"
